### ISSUE TITLE
Can this plugin work with ForkTsChecker plugin when clearConsole is true?

### ISSUE THREAD

**Issue by TotooriaHyperion** [geowarin/friendly-errors-webpack-plugin#116]
Can this plugin work with ForkTsChecker plugin?
fork ts checker plugin work in a different worker, so if compile complete after the ts check, the ts c heck information in console will be cleared.
Is there any method to include ForkTsChecker's output in to this plugin?
I mean, if find a new ForkTsChecker output, combine it with the latest compilation result and refresh the console with combined information.

**Comment by nieshiming** [comment]
@TotooriaHyperion   How did you solve this problem

**Comment by TotooriaHyperion** [comment]
@nieshiming 
https://github.com/TotooriaHyperion/delay-fork-ts-output-plugin
replace fork-ts-checker's logger, save the latest ts check result, log it after the last compile.

**Comment by nieshiming** [comment]
@TotooriaHyperion  i fixed problem,    The reason is because ts is not finalized into js，   i adjust  eslint-loader to happy-pck solve ,   eg: 

before:
```
      {
        test: /\.js$/,
        exclude: '/node_modules/',
        loader: 'eslint-loader',
        include: [source]
      },
      {
        test: /\.(js|ts)x?$/,
        exclude: '/node_modules/',
        loader: ['happypack/loader?id=js'],
        include: [source]
      }
```

after:
```
    new HappyPack({
      id: 'js',
      threads: happyThreadPool.size,
      loaders: [
        {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true
          }
        },
        {
          loader: 'eslint-loader'
        }
      ]
    })
```

**Comment by TotooriaHyperion** [comment]
this seems doesn't ensure the log order.
I don't understand what 'finalize into js' mean. I didn't use happypack.
我觉着我们直接说中文吧QwQ

Levi <notifications@github.com> 于 2020年4月28日周二 19:32写道：

**Comment by nieshiming** [comment]
@TotooriaHyperion  我在ts项目中，特意require错误js路径时候，js文件弹框报错了，证明配置可以使用js文件，应该是eslint 配置@typescript-eslint没有生效，然后我就把eslint-loader放在babel-loader之后，然后就成功了~不过我用的webpack4.0 + happypck做的

**Comment by nieshiming** [comment]
@TotooriaHyperion   刚才验证不用happypack也是可以，是loader加载顺序问题
```
      {
        test: /\.(js|ts)x?$/,
        exclude: '/node_modules/',
        loader: ['babel-loader', 'eslint-loader'],
        include: [source]
      }
```

**Comment by nieshiming** [comment]
https://imweb.io/topic/5d4a94a08db073cf44ca8cd0

**Comment by TotooriaHyperion** [comment]
@nieshiming 我有点看不懂你的问题。loader本来就是从后向前的。你把eslint放在babel前面，会导致eslint检查的是babel编译后的文件，而不是你原本的文件。有大量报错是很正常的。但是这个并不影响log顺序，因为多个loader不是异步执行的，而且happypack也是所有线程跑完统一输出的。我这边的问题是因为ForkTsChecker是异步输出的，偶尔会覆盖FriendlyErrors的输出，所以我要delay以下。

**Comment by nieshiming** [comment]
@TotooriaHyperion  那我俩还是不一样的问题...zzz
