### ISSUE TITLE
Loader string attached to file path

### ISSUE THREAD

**Issue by MatteoGabriele** [geowarin/friendly-errors-webpack-plugin#15]
when applying loaders with few options, the output of the file path is usually pretty long because is holding the entire loader string with it.
Example of a warning prompt by eslint
 
```bash
Warning in ../blocklevel/blue-next/packages/bcli/~/babel-loader/lib?presets[]=/web/blocklevel/blue-next/packages/bcli/~/babel-preset-es2015/lib/index.js&presets[]=/web/blocklevel/blue-next/packages/bcli/~/babel-preset-stage-2/lib/index.js&plugins[]=/web/blocklevel/blue-next/packages/bcli/~/babel-plugin-transform-runtime/lib!../blocklevel/blue-next/packages/bcli/~/eslint-loader?configFile=/web/blocklevel/blue-next/packages/eslint-config-blocklevel!./src/app/page/home/home.js
```
Is it possible to extract only the actual file path, in this case `/src/app/page/home/home.js`, without its entire loader string?

**Comment by geowarin** [comment]
Yes it should be!
Would you be willing to include a repro or, even better, a test so I can have a look ?

**Comment by MatteoGabriele** [comment]
I'm working in a private repo and I can't make it public, but I should be able to arrange something that works the same way and publish it somewhere else. 
Thanks!

**Comment by MatteoGabriele** [comment]
I've just created a very simple repo with a webpack structure that shows this issue.
Just install node packages and run `npm run dev`. I've wrote some code that on purpose shows up in the terminal because the linter doesn't allow me to write it.

The code that comes from the `vue-loader` has a long file path due to its loader that needs to be written as a single string, so combining long loaders, that's the result.

Repository: https://github.com/MatteoGabriele/webpack-dev-server-test/tree/master

<img width="1190" alt="image 2017-01-15 at 10 53 17 pm" src="https://cloud.githubusercontent.com/assets/5337152/21966543/924622ee-db75-11e6-8262-e1491f2e681b.png">

**Comment by geowarin** [comment]
Should be fixed in 1.1.3.
I will keep this issue open because I could not include a simple repro of your problem.

**Comment by geowarin** [comment]
I mean your repro was superb (thanks btw!), but I don't want to include the whole vue setup in the tests so I have to look for even simpler

**Comment by MatteoGabriele** [comment]
Thanks a lot!
I've added `vue` because was easier to copy paste here and there from the project i was working on. It's working now, the only thing that is still there is that strange list of files at the end, where the original long string is still listed, but i don't know if it's the plugin or some setting of webpack that i have to remove: what you think?

<img width="713" alt="image 2017-01-16 at 7 54 00 am" src="https://cloud.githubusercontent.com/assets/5337152/21973504/7dd22b18-dbc1-11e6-8fca-6e28e693062e.png">

**Comment by MatteoGabriele** [comment]
Actually on the repo I wrote for this issue, everything works perfectly, not even that kind of stack trace at the bottom. Maybe then is some other option I have in webpack, but looks like is inside your plugin console. Let me know if you have any idea, in the meantime I will write a less heavy repo to see if i can reproduce it.

**Comment by geowarin** [comment]
Thanks for your involvement @MatteoGabriele, really appreciated.

I suspect the "stack trace" is the origin of the error, it is unclear in which context webpack provides this information.
We decided to include the origin, if available in [the default formatter](https://github.com/geowarin/friendly-errors-webpack-plugin/blob/master/src/formatters/defaultError.js#L13) but we could decide not to in case of a lint error.

In all cases, simple repros are really important as webpack is kind of a black box we have to build on.

**Comment by MatteoGabriele** [comment]
Yeah would be nice to have an optional stack trace log.
Thanks again.

**Comment by MatteoGabriele** [comment]
Nothing I tried several setup but, can't reproduce the errors without adding `vue`, maybe it was the culprit. Let me know just if you are going to make the stack trace optional, that would be nice.

Thanks again for your quick updates.
