### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by aight8** [geowarin/friendly-errors-webpack-plugin#24]
```
  TypeError: Cannot read property 'indexOf' of undefined
  
  - esLintError.js:7 e.originalStack.some.stackframe
    [zzz]/[friendly-errors-webpack-plugin]/src/transformers/esLintError.js:7:44
  
  - Array.some
  
  - esLintError.js:11 transform
    [zzz]/[friendly-errors-webpack-plugin]/src/transformers/esLintError.js:11:7
  
  - Array.reduce
  
  - Array.map
  
  - friendly-errors-plugin.js:86 FriendlyErrorsWebpackPlugin.displayErrors
    [zzz]/[friendly-errors-webpack-plugin]/src/friendly-errors-plugin.js:86:29
  
  - friendly-errors-plugin.js:51 Compiler.compiler.plugin.stats
    [zzz]/[friendly-errors-webpack-plugin]/src/friendly-errors-plugin.js:51:14
  
  - Tapable.js:61 Compiler.applyPlugins
    [zzz]/[tapable]/lib/Tapable.js:61:14
  
  - Compiler.js:227 onCompiled
    [zzz]/[webpack]/lib/Compiler.js:227:12
  
  - Compiler.js:480 
    [zzz]/[webpack]/lib/Compiler.js:480:13
  

error Command failed with exit code 1.
```

**Comment by geowarin** [comment]
Hello, which version of node do you use ?
I have updated the stackframe library recently, we could easily rollback.

I'm curious why CI did not catch this error thought...

**Comment by geowarin** [comment]
Can you reproduce the error with version 1.1.3 ?

**Comment by geowarin** [comment]
Should be fixed in [v1.3.1](https://github.com/geowarin/friendly-errors-webpack-plugin/releases/tag/v1.3.1). Please test it and tell me if it worked :smile:

**Comment by aight8** [comment]
I'm using node v7.4.0.

I currently testing it, but I think there was some massive conflict with another package called "pretty-error".

**Comment by geowarin** [comment]
I think the check has its place in the codebase, better safe than sorry.

Yes, it's weird: it could happen if webpack throws an error without having an original stacktrace (loader or something).

I've never seen it happen but, you know, webpack :neckbeard:

I'm curious to have your final diagnostic, though

**Comment by geowarin** [comment]
Yup, pretty errors [messes up](https://github.com/AriaMinaei/pretty-error/blob/master/src/PrettyError.coffee#L45) with stackframes.
Maybe you should open a bug there ?

**Comment by aight8** [comment]
Yeah webpack can be really funny.

The structure was something like:
```
{ fileName: '\u001b[0m  \u001b[0m\u001b[97mParent style sheet: stdin\u001b[0m',
    source: '\u001b[0m  \u001b[0m\u001b[97mParent style sheet: stdin\u001b[0m' },
  { functionName: '\u001b[0m  \u001b[0m\u001b[97m      in /zzz/blabla.scss (line 2, column 1)\u001b[0m' },
  { functionName: '\u001b[0m  \u001b[0m' },
```

**Comment by aight8** [comment]
Yep why not - it's always good if library don't disturb each other. I honestly have not much insights about both libs, just found ```friendly-errors-webpack-plugin``` before a hour :P So I currently cannot describe a change suggestion in their repo.

**Comment by aight8** [comment]
Wondering if you plan to merge some other common transformers etc. which are used a lot by webpack? I currently try to write custom ones but must research the code because the readme missing the function signatures and the error object structure. I try & error now...

**Comment by geowarin** [comment]
So I guess you could come up this the following repro if I understand the problem correctly:

```js
require('pretty-error').start();
const stack = ErrorStackParser.parse(new Error())
expect(stack.all(s => typeof s.fileName === 'string')).toBeTruthy()
```
