### ISSUE TITLE
Use pretty-cli ?

### ISSUE THREAD

**Issue by geowarin** [geowarin/friendly-errors-webpack-plugin#3]
See this nice looking PR for create-react-app: https://github.com/facebookincubator/create-react-app/pull/461

**Comment by rogeliog** [comment]
That looks quite nice

**Comment by MichaelCereda** [comment]
Hello, I noticed you linked the PR I made on create-react-app.
If you're interested in doing something similar we can get in touch.
Have a nice day.

**Comment by geowarin** [comment]
Hello @MichaelCereda!
I love your PR and the idea of pretty-cli. I think it would fit nicely with what we're trying to achieve with this module.

I think we could change our current notion of [formatters](https://github.com/geowarin/friendly-errors-webpack-plugin/blob/333bad87aeca731018c56f8c18a5ae71adbc5616/src/core/formatErrors.js) and plug pretty-cli templates in them.

I'll try to figure something out after we release 1.0 (it's a nice to have) but if you feel like our goals are aligned and wish to work on a PR, that would be awesome 😄

**Comment by geowarin** [comment]
Finally I decided to adopt a look that is very closed to what pretty-cli offered but without additional dependency.
Thanks @MichaelCereda for the inspiration 😄 

Fix in 931bf4e13ea0816a44a9bb875610eda6ca5688d6
