### ISSUE TITLE
Support double byte characters in output.title timestamp

### ISSUE THREAD

**Issue by cncolder** [geowarin/friendly-errors-webpack-plugin#43]
Currently `output.title` get timestamp by [string-length](https://github.com/sindresorhus/string-length)

I got log like this:

```bash
 DONE  Compiled successfully in 150ms                               下午11:15:
57
```

![double byte timestamp](https://cloud.githubusercontent.com/assets/127009/24073555/0e082e56-0c34-11e7-8914-fa0a4e2c7489.png)

I suggest replace it with [string-width](https://github.com/sindresorhus/string-width)

**Comment by geowarin** [comment]
Hello @cncolder and thanks for the suggestion.
Would you be able to open a PR and fix the bug?
