### ISSUE TITLE
Not formatting webpack-dev-server start-up?

### ISSUE THREAD

**Issue by alexandernanberg** [geowarin/friendly-errors-webpack-plugin#48]
With my current set-up the start-up process with webpack-dev-server is not formatted like in your [demos](https://github.com/geowarin/friendly-errors-webpack-plugin#demo) instead it looks like this

![image](https://cloud.githubusercontent.com/assets/8997319/25433582/1ccf3f74-2a89-11e7-9fb4-ddb7ac5816de.png)

[My webpack config](https://github.com/alexandernanberg/minimal-react-boilerplate/blob/master/webpack.config.js)

Have I configured it wrong or is it a bug? Would love for it to work like in the demos! 😄

**Comment by IgnusG** [comment]
I have exactly the same problem: Running webpack 2.4.1 & webpack-dev-server 2.4.5

**Comment by geowarin** [comment]
Hello gentlemen!

Did you expect to see the screen get cleared just before the DONE notification?
Does it get cleared correctly on subsequent messages?

**Comment by alexandernanberg** [comment]
I was expecting to see something similar to this

![demo](https://camo.githubusercontent.com/8626811b709addc6e4e953b1ed2d3414fc843522/687474703a2f2f692e696d6775722e636f6d2f4d6b554568597a2e676966)

The screen clears as expected but I'm not seeing the "Starting the development server..." text. Also not seeing the "Your application is accessible at http://localhost:3000"

**Comment by geowarin** [comment]
That's normal, the plugin has no easy means to know on which port the server is available.
You should manually add the [compilationSuccessInfo](https://github.com/geowarin/friendly-errors-webpack-plugin#options) for this to work

**Comment by alexandernanberg** [comment]
Ah so that message will be displayed every time it compiles successfully then? Thought it only displayed on start up/first compilation.

What about the "Starting development server..." log, similar issue?

**Comment by geowarin** [comment]
Yes, it is displayed every time the compilation succeeds.
Originally, we cleared the console for good so it was useful to have those info available very time.

Since #23, it's debatable.
I don't think "Starting development server..." is part of the plugin output.

**Comment by alexandernanberg** [comment]
Oh okay! Closing this then, thanks for your response!
