### ISSUE TITLE
Display bundle sizes

### ISSUE THREAD

**Issue by timneutkens** [geowarin/friendly-errors-webpack-plugin#54]
@geowarin what's your opinion on this:
https://github.com/zeit/next.js/issues/876

**Comment by MaxMilton** [comment]
This plugin is meant to be used during development at which time bundle sizes are not relevant. Showing bundle sizes is only valuable during production builds since that's when all the extra minification etc. happens.

**Comment by timneutkens** [comment]
Fair point @MaxMilton.
