### ISSUE TITLE
Filter warning/errors messages

### ISSUE THREAD

**Issue by mribichich** [geowarin/friendly-errors-webpack-plugin#75]
Hi there, It would be great if one could filter messages like [dev-server](https://webpack.js.org/configuration/stats/) already does

something like this:

```
    // Filter warnings to be shown (since webpack 2.4.0),
    // can be a String, Regexp, a function getting the warning and returning a boolean
    // or an Array of a combination of the above. First match wins.
    warningsFilter: "filter" | /filter/ | ["filter", /filter/] | (warning) => true|false
```

**Comment by VladimirGrenaderov** [comment]
There is a workaround - simple plugin to clear stats before compilation was done:

```typescript
interface Options {
  filter: RegExp;
}

class FilterPlugin implements Plugin {
  constructor(private readonly options: Options) {}

  apply(compiler: Compiler) {
    compiler.hooks.afterEmit.tap(
      'FilterPlugin',
      compilation => {
        compilation.warnings = (compilation.warnings as Error[]).filter(
          warning => !this.options.filter.test(warning.message)
        );
      }
    );
  }
}

**Comment by valjusha** [comment]
How using this code?

**Comment by mribichich** [comment]
just in case there is also a plugin that does exactly the same:

https://github.com/mattlewis92/webpack-filter-warnings-plugin

thanks!

**Comment by huww98** [comment]
I'm not very familiar with webpack, but can we just support this config? https://webpack.js.org/configuration/stats/#statswarningsfilter

I'm using [vue-cli](https://cli.vuejs.org), and it is using this plugin. but I'm not realized that. I've been trying to disable a warning for hours before I see this. Setting the config from official doc but it never taking effect is very frustrating.
