### ISSUE TITLE
Webpack-dev-server 'quiet: true' but errors are shown in console

### ISSUE THREAD

**Issue by sweetkat** [geowarin/friendly-errors-webpack-plugin#76]
When `devServer` flag is set to `quiet: true` I still see eslint errors thrown in console. Once I remove `friendly-errors-webpack-plugin` all errors are hidden. 
Running`webpack: 4.1.6`, `webpack-dev-server: 3.1.5` and `friendly-errors-webpack-plugin: 1.7.0`.
Is there some other magic setting missing?

**Comment by christophehurpeau** [comment]
Follow the updated documentation: https://github.com/geowarin/friendly-errors-webpack-plugin#turn-off-errors
