### ISSUE TITLE
Support MultiCompiler / MultiStats

### ISSUE THREAD

**Issue by richardscarrott** [geowarin/friendly-errors-webpack-plugin#8]
`webpack(config)` returns a [`MultiCompiler`](https://github.com/webpack/webpack/blob/master/lib/MultiCompiler.js) if your config is [an array of configurations](https://webpack.github.io/docs/configuration.html#multiple-configurations) and `multiCompiler.plugin('done', multiStats => {});` provides [`MultiStats`](https://github.com/webpack/webpack/blob/master/lib/MultiCompiler.js#L190) meaning this plugin could potentially receive a `MultiCompiler` instance.

Currently it works well with the `MultiCompiler` as it only uses the `plugin` method which is supported on the `MultiCompiler`.

It falls down however when interfacing with the `MultiStats` instance as it looks something like this:

```
{
    stats: [
        Stats,
        Stats
    ]
}
```

So it would need to get errors and warnings from each of those child `Stats` instances.

The other problem is it reads `DONE  Compiled successfully in NaNms` because `stats.startTime` and `stats.endTime` don't exist on `MultiStats`, it'd have to be calculated from both of the child stats.

I'm not sure if this is something you want to support as it is possible to simply apply the plugin to both compilers separately but it means stdout will be flushed to twice so I think it would only show the error from one of the compilations, regardless of 'severity'. Also, the build time would only reflect one of the compilations....not sure if there would be any other implications you can think of with this approach?

As an aside, great work on the plugin -- makes all the difference during development!

**Comment by richardscarrott** [comment]
Okay, I've discovered applying the plugin to both compilers separately doesn't really work because the console may read 'DONE' because the most recent compilation succeeded but it obviously doesn't take into account the other compilation which may still be in an error state.

Would you be open to a PR for this?

**Comment by geowarin** [comment]
Hi @richardscarrott, I'll accept any PR with tests 😄 
Thanks for taking the time to document this issue!

**Comment by geowarin** [comment]
Fixed in #9

**Comment by DylanPiercey** [comment]
What does the config look like to use this with a multi compiler? Do I add the plugin to both compilers?

**Comment by richardscarrott** [comment]
@DylanPiercey you'll need to apply the plugin to the the multi compiler returned from `webpack`, e.g. https://github.com/60frames/react-boilerplate/blob/master/server/routes/webpack.js#L20


```
const multiCompiler = webpack([config1, config2]);
multiCompiler.apply(new FriendlyErrorsWebpackPlugin());
```

**Comment by DylanPiercey** [comment]
@richardscarrott awesome - thanks! Gonna try this out now.

**Comment by DylanPiercey** [comment]
It works perfectly :D.
