### ISSUE TITLE
should not output warning when the count of warnings is 0

### ISSUE THREAD

**Issue by lovetingyuan** [geowarin/friendly-errors-webpack-plugin#84]
> WARNING  Compiled with 0 warnings

so you should not print the message above as the number of warnings is 0.

**Comment by see365** [comment]
the same issue

**Comment by christophehurpeau** [comment]
Can you check if it is still the case with `2.0.0-beta.1` ?

**Comment by Lyrkan** [comment]
Hi @christophehurpeau,

We had a similar issue opened on the Webpack Encore repository (https://github.com/symfony/webpack-encore/issues/593) that I can also reproduce using our `master` branch (that targets `2.0.0-beta.1`).

When that happens `stats.hasWarning()` returns `true` so it goes into the following `if`:

https://github.com/geowarin/friendly-errors-webpack-plugin/blob/273ca3b19d4f8191604836ffcf61286596ee9477/src/friendly-errors-plugin.js#L56-L58

But `stats.compilation.warnings` returns an empty array here:

https://github.com/geowarin/friendly-errors-webpack-plugin/blob/273ca3b19d4f8191604836ffcf61286596ee9477/src/friendly-errors-plugin.js#L145

Here is a repro provided by @uturnr if you want to take a look: https://github.com/uturnr/webpack-encore-repro-issue-593

**Comment by Lyrkan** [comment]
After looking at that issue a bit more I think it happens because the `extractErrorsFromStats()` function stops at the first compilation object instead of also looking in its children.

I tried with the following code and now get `WARNING  Compiled with 1 warnings`, but still no warning message for some reason (it may be another issue though)...

```js
function extractErrorsFromStats(stats, type) {
  if (isMultiStats(stats)) {
    const errors = stats.stats
      .reduce((errors, stats) => errors.concat(extractErrorsFromStats(stats, type)), []);
    // Dedupe to avoid showing the same error many times when multiple
    // compilers depend on the same module.
    return uniqueBy(errors, error => error.message);
  }

  const findErrorsRecursive = (compilation) => {
    const errors = compilation[type];
    if (compilation.children) {
      for (const child of compilation.children) {
        errors.push(... findErrorsRecursive(child));
      }
    }

    // Not sure if the uniqueBy is needed here...
    return uniqueBy(errors, error => error.message);
  };

  return [findErrorsRecursive(stats.compilation)];
}
```
