### ISSUE TITLE
Does not work with Node.js v12

### ISSUE THREAD

**Issue by moritzruth** [geowarin/friendly-errors-webpack-plugin#88]
I get this error when running webpack with the plugin:
```
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ffc4c0f7a70
```

webpack: 4.31.0
friendly-errors-webpack-plugin: 1.7.0
Node.js: 12.0.0

**Comment by sodatea** [comment]
That’s a bug in Node.js v12.0.0 and you should upgrade your node version

**Comment by christophehurpeau** [comment]
@sodatea thank you for the solution :)
